# Site settings
title: "BAIL Lab Instructions"
description: "Essential guides and instructions for the BAIL Lab"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site configuration
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site author
author:
  name: "BAIL Lab"
  bio: "Lab instructions and guides"

# Reading files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  # _docs
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs"

navigation:
  docs:
    - title: Getting Started
      url: /
    - title: Network Guides
      children:
        - title: "Windows Network Setup"
          url: /docs/windows-network/
        - title: "Mac Network Setup"
          url: /docs/mac-network/
    - title: Printer Guides
      children:
        - title: "Windows Printer Setup"
          url: /docs/windows-printer/
        - title: "Mac Printer Setup"
          url: /docs/mac-printer/
