# Set the theme to Just the Docs
remote_theme: just-the-docs/just-the-docs

# The title of your site
title: BAIL Lab Instructions

# A short description of your site
description: Guides for accessing and using lab resources

# Optional: Add a footer message
footer_content: "Contact Thanu (thanu56@uw.edu) for access or issues"
